//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adopcion
    {
        public int id_adopcion { get; set; }
        public int id_usuario { get; set; }
        public int id_mascota { get; set; }
        public System.DateTime fecha_adopcion { get; set; }
    
        public virtual Mascota Mascota { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
