//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donacion
    {
        public int id_donacion { get; set; }
        public decimal monto { get; set; }
        public string nombre_donante { get; set; }
        public string email_donante { get; set; }
        public string metodo_pago { get; set; }
        public string numero_tarjeta { get; set; }
        public Nullable<System.DateTime> fecha_expiracion { get; set; }
        public string codigo_seguridad { get; set; }
        public System.DateTime fecha_donacion { get; set; }
    }
}
