//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donacion
    {
        public int id_donacion { get; set; }
        public decimal monto { get; set; }
        public string nombre_donante { get; set; }
        public string email_donante { get; set; }
        public string metodo_pago { get; set; }
        public string numero_tarjeta { get; set; }
        public System.DateTime fecha_expiracion { get; set; }
        public string codigo_seguridad { get; set; }
        public System.DateTime fecha_donacion { get; set; }
    }
}
